In [2]:
DIR = "./dataset/minutae/"
import pandas as pd
import numpy as np

In [16]:
df=pd.read_csv(filename, sep=' ',header=None)
df = np.array(df)
print(df)
print(df.shape)
np.sort(df, axis=0)
df = df[df[:,3].argsort()[::-1]]
print(df)
print(df.shape[0])

[[122  34 140   4]
 [342  54 120  90]
 [343 121   7  77]
 [121 435  54  54]
 [456 424 123  65]
 [ 35  76  23   7]]
(6, 4)
[[342  54 120  90]
 [343 121   7  77]
 [456 424 123  65]
 [121 435  54  54]
 [ 35  76  23   7]
 [122  34 140   4]]
6


In [37]:
def crop_top(df,crop_size):
    #this will take top n inputs for df
    if df.shape[0]<crop_size:
        d_zero = np.zeros((crop_size,df.shape[1]), dtype=int)
        d_zero[:df.shape[0], :df.shape[1]]=df
        return d_zero
    else:
        return df[0:crop_size,:]

In [ ]:
normalization_factor = np.array([512,512,360,100])
df_new = crop_top(df,2)/normalization_factor